subscribers:
  - name:        "Misc"
    topic:       "input/misc/cmd_vel"
    timeout:      0.5
    priority:     0
    short_desc:  "Cmd_vel input for anything not otherwise accounted for"

  - name:        "Nav stack"
    topic:       "input/nav/cmd_vel"
    timeout:     0.5
    priority:    1
    short_desc:  "Navigation stack controller"

  - name:	 "Keyboard"
    topic:	 "input/keyboard/cmd_vel"
    timeout:	 0.5
    priority:	 2
    short_desc:  "Keyboard controls"

  - name:        "Spacenav"
    topic:       "input/spacenav/cmd_vel"
    timeout:     0.5
    priority:    3
    short_desc:  "Spacenav controls"

  - name:        "Joystick"
    topic:       "input/joy/cmd_vel"
    timeout:     0.5
    priority:    4
    short_desc:  "Joystick controls"

publisher: "cmd_vel"
