# Robot Configuration Parameters
acc_lim_x: 2.5
acc_lim_y: 2.5
acc_lim_th: 3.2
max_vel_x: 2.68
min_vel_x: 0.1
max_rotational_vel: 1.75
min_in_place_rotational_vel: 0.8
escape_vel: -0.1
holonomic_robot: false
meter_scoring: false
# Goal Tolerance Parameters

#Origial Tolerances
#xy_goal_tolerance: 0.1
#yaw_goal_tolerance: 0.2

xy_goal_tolerance: 0.5
yaw_goal_tolerance: 0.5


# Forward Simulation Parameters
sim_time: 2.7
sim_granularity: 0.025
vx_samples: 14
vtheta_samples: 40

# Trajectory Scoring Parameters
goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01
heading_lookahead: 0.325
dwa: true


# Oscillation Prevention Parameters
oscillation_reset_dist: 0.025
