#!/usr/bin/env bash

# Much of this was adapted from husky_bringup

LOCAL_LOG_DIR="$HOME/ros_logs"
source `rospack find rosbash`/rosbash
echo "export LOCAL_LOG_DIR=$LOCAL_LOG_DIR" > `rospack find wheelchair_bringup`/env/vars.bash
ROBOT_SETUP=`rospack find wheelchair_bringup`/env/setup.bash

echo "Installling udev rules"
rospd wheelchair_bringup/udev > /dev/null
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
sudo udevadm trigger

echo "Installing launch files"
# For the setup.bash to use, first try ROBOT_SETUP, then fall back on setup.bash from active workspace.
install_pkg="rosrun robot_upstart install"
$install_pkg wheelchair_bringup/launch/hokuyo_multi.launch --job wheelchair-lasers \
                                                           --interface wlan0 \
                                                           --setup ${ROBOT_SETUP-$(roscd; echo `pwd`/setup.bash)}

$install_pkg wheelchair_bringup/launch/logging.launch      --job wheelchair-logging \
                                                           --interface wlan0 \
                                                           --setup ${ROBOT_SETUP-$(roscd; echo `pwd`/setup.bash)}

# Configure logging
echo "Configuring logging"
echo "Logging to $LOCAL_LOG_DIR"
mkdir -p $LOCAL_LOG_DIR
`rospack find wheelchair_bringup`/rosbag-rotate/setup.sh $LOCAL_LOG_DIR billsmart.mime.oregonstate.edu wheelchair_logs
