#!/usr/bin/env bash

source `rospack find rosbash`/rosbash

echo "Installling udev rules"
# TODO udev rules

# Much of this was adapted from husky_bringup
echo "Installing launch files"

# For the setup.bash to use, first try ROBOT_SETUP, then fall back on setup.bash from active workspace.
install_pkg="rosrun robot_upstart install"
$install_pkg wheelchair_bringup/launch/hokuyo_multi.launch --job wheelchair-lasers \
                                                           --interface wlan0 \
                                                           --setup ${ROBOT_SETUP-$(roscd; echo `pwd`/setup.bash)}

# Configure logging
LOCAL_LOG_DIR="~/ros_logs"
mkdir -p $LOCAL_LOG_DIR
./rosbag-rotate/setup.sh $LOCAL_LOG_DIR billsmart.mime.oregonstate.edu wheelchair_logs
