#!/usr/bin/env python

import sys
import rospy

from rqt_runstop.rqt_runstop_module import RunStopPlugin
from rqt_gui.main import Main
from actionlib_msgs.msg import GoalID

def main():
	plugin = 'rqt_runstop'
	main = Main(filename=plugin)
	sys.exit(main.main(standalone=plugin))


if __name__ == "__main__":
    main()